### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by HDValentin**
Translated, corrected and approved around 880 expressions in German

### CODE REVIEW

**Comment by steevhise** [comment]
Hi Valentin - I thought you'd gotten out of doing this a while ago. ??
Anyway, we're transitioning to a new system for managing translations, and also the site is changing soon to the new version, so this repo isn't really all that relevant any more.  I'm also confused looking at the diffs - is this commit something you did long ago and forgot to push til now? cuz every single line is different.
Anyway, please let Deron know if you're interested in helping out with translation going forward, with our new system, which uses an online service called Lokalise. it's pretty slick. thanks!

**Comment by HDValentin** [comment]
No, sadly I made this work yesterday.
Could you please close this repo please?
I thought i is active.

**Comment by steevhise** [comment]
I am sorry for your efforts that might go to waste! 
We're still using the repo as we are still transitioning to the new process, we're just not taking PRs. Yesterday I closed the issue in which I asked you and Marina for help, which was a year or so old. Is that what led to the confusion?  Again, my apologies, I was under the impression (told by Deron months ago) that you weren't involved with volunteering in this way any more.

**Comment by HDValentin** [comment]
Hi Steeve, yes your closed ticket encouraged me to look into the project and see what's going on. :-) Yes, I told Deron, that I am off.

**Pull request closed without merging**
