### PR TITLE
Master

### PR DESCRIPTION
**Pull request by mvaillan**

### CODE REVIEW

**Comment by steevhise** [comment]
I ended up doing this by hand, now a while ago!

**Comment by mvaillan** [comment]
Hello,
what are you talking about?

Marina

2016-02-19 0:20 GMT+01:00 Steev Hise <notifications@github.com>:

**Comment by steevhise** [comment]
This is a pull request you submitted back in December, which I took care of then, but I just noticed it was still open, so I was just closing it.

**Comment by mvaillan** [comment]
ok :)
I have started to translate the remaining sentences, from the file you sent
me last month.
I'm having a break right now but I'll try to finish it before sending it
back.

Marina

2016-02-19 17:57 GMT+01:00 Steev Hise <notifications@github.com>:

**Pull request closed without merging**
